# -*- coding: utf-8 -*-
"""
=====================================================================
🏆 FastAPI Model Serving Server
=====================================================================
Author: Muhammad Roman Khan
Repository: Course 1 Capstone Deployment API

Description:
This production-ready FastAPI server loads my serialized model pipelines 
(housing_price_model.pkl and deal_quality_model.pkl) and exposes REST endpoints 
to serve predictions dynamically for price (regression) and quality (classification).

Run the server using:
    uvicorn app:app --reload
=====================================================================
"""

import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
import joblib
import numpy as np

app = FastAPI(
    title="Housing Market Prediction API",
    description="Exposes my prediction endpoints for house prices and deal quality.",
    version="1.0"
)

# Load my serialized pipelines
REG_MODEL_PATH = "housing_price_model.pkl"
CLF_MODEL_PATH = "deal_quality_model.pkl"

if not os.path.exists(REG_MODEL_PATH) or not os.path.exists(CLF_MODEL_PATH):
    # Warning if models haven't been generated by capstone_runner.py
    print("[WARNING] Serialized models not found. Run capstone_runner.py first to generate them.")
    reg_pipeline = None
    clf_pipeline = None
else:
    reg_pipeline = joblib.load(REG_MODEL_PATH)
    clf_pipeline = joblib.load(CLF_MODEL_PATH)
    print("[SUCCESS] Serialized models loaded successfully.")

# =====================================================================
# 1. MY REQUEST AND RESPONSE SCHEMAS
# =====================================================================
class HouseFeatures(BaseModel):
    size: float = Field(..., example=1800.0, description="Size of the house in square feet")
    bedrooms: float = Field(..., example=3.0, description="Number of bedrooms (1 to 5)")
    age: float = Field(..., example=12.0, description="Age of the property in years")
    tax_rate: float = Field(..., example=2.1, description="Local tax rate in percentage")

class PricePredictionResponse(BaseModel):
    predicted_price: float
    input_features: HouseFeatures

class DealPredictionResponse(BaseModel):
    deal_probability: float
    is_premium_deal: int
    input_features: HouseFeatures

# =====================================================================
# 2. MY API ENDPOINTS
# =====================================================================
@app.get("/")
def read_root():
    return {
        "message": "Welcome to my Housing Market API!",
        "endpoints": {
            "POST /predict_price": "Predicts house price (Ridge Regression)",
            "POST /predict_deal": "Predicts if a house is a Premium Deal (Logistic Regression)"
        }
    }

@app.post("/predict_price", response_model=PricePredictionResponse)
def predict_price(house: HouseFeatures):
    if reg_pipeline is None:
        raise HTTPException(status_code=500, detail="Regression model not trained/loaded.")
    
    # Format inputs into shape (1, n)
    input_data = np.array([[house.size, house.bedrooms, house.age, house.tax_rate]])
    
    # Run predictions
    prediction = reg_pipeline.predict(input_data)[0]
    
    return PricePredictionResponse(
        predicted_price=round(float(prediction), 2),
        input_features=house
    )

@app.post("/predict_deal", response_model=DealPredictionResponse)
def predict_deal(house: HouseFeatures):
    if clf_pipeline is None:
        raise HTTPException(status_code=500, detail="Classification model not trained/loaded.")
    
    # Format inputs
    input_data = np.array([[house.size, house.bedrooms, house.age, house.tax_rate]])
    
    # Predict positive probability [P(y=0), P(y=1)]
    prob_positive = clf_pipeline.predict_proba(input_data)[0][1]
    
    # Predict class (0 or 1) using standard 0.5 threshold
    predicted_class = int(clf_pipeline.predict(input_data)[0])
    
    return DealPredictionResponse(
        deal_probability=round(float(prob_positive), 4),
        is_premium_deal=predicted_class,
        input_features=house
    )
